export { Main } from "./Main";
export { SEO } from "./SEO";

export { Hero } from "./UI/Hero";
export { Carusel } from "./UI/Carusel";
export { BlogCarusel } from "./UI/BlogCarusel";
export { CardsCarusel } from "./UI/CardsCarusel";
export { TextImage } from "./UI/TextImage";
export { TextImageOne } from "./UI/TextImageOne";
export { TextImageTwo } from "./UI/TextImageTwo";
export { TextGridImages } from "./UI/TextGridImages";
export { TextGridThreeImages } from "./UI/TextGridThreeImages";
export { BannerCarusel } from "./UI/BannerCarusel";
export { FeaturedPosts } from "./UI/FeaturedPosts";
export { BlogCaruselTwoSlides } from "./UI/BlogCaruselTwoSlides";
export { Propiedades } from "./UI/Propiedades";
export { Forms } from "./UI/Forms";
export { Items } from "./UI/Items";
export { ImagesTextsItems } from "./UI/ImagesTextsItems";